-- Deprecated compatibility entrypoint.
-- The canonical PostgreSQL schema is server/scripts/rebuild_schema.sql.
-- Use:
--   node server/scripts/run_rebuild.js
-- or:
--   psql "$DATABASE_URL" -f server/scripts/rebuild_schema.sql
