const ROLES = Object.freeze({
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  MIDWIFE: 'Midwife',
  NURSE: 'Nurse',
  BHW: 'BHW',
  CAREGIVER: 'Caregiver'
});

const STAFF_ROLES = Object.freeze([
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.MIDWIFE,
  ROLES.NURSE,
  ROLES.BHW
]);

const REGISTRATION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_VALIDATION: 'PENDING_VALIDATION',
  NEEDS_CORRECTION: 'NEEDS_CORRECTION',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
});

const IMMUNIZATION_STATUS = Object.freeze({
  FULLY_IMMUNIZED: 'FULLY_IMMUNIZED',
  UP_TO_DATE: 'UP_TO_DATE',
  DUE_SOON: 'DUE_SOON',
  OVERDUE: 'OVERDUE',
  DEFAULTED: 'DEFAULTED',
  INCOMPLETE: 'INCOMPLETE'
});

const CLINICAL_STATUS = IMMUNIZATION_STATUS;

const SCHEDULE_STATUS = Object.freeze({
  NOT_YET_DUE: 'NOT_YET_DUE',
  DUE_SOON: 'DUE_SOON',
  DUE_TODAY: 'DUE_TODAY',
  DEFAULTER: 'DEFAULTER',
  OVERDUE: 'OVERDUE',
  DEFAULTED: 'DEFAULTED',
  COMPLETED: 'COMPLETED',
  PENDING_VALIDATION: 'PENDING_VALIDATION',
  INELIGIBLE: 'INELIGIBLE'
});

module.exports = {
  ROLES,
  STAFF_ROLES,
  REGISTRATION_STATUS,
  CLINICAL_STATUS,
  IMMUNIZATION_STATUS,
  SCHEDULE_STATUS
};
